// Fight Timer - offline cache. GENERATED by tools/build.mjs; do not edit.
const CACHE = 'fight-timer-830eaa71';
const CORE = [
  "./",
  "./index.html",
  "./manifest.webmanifest",
  "./app-a8871dc7ca.js",
  "./app-436c10bad0.css",
  "./logo.png",
  "./favicon-32.png",
  "./fonts/chakra-petch-600-latin-4d6d5f0b.woff2",
  "./fonts/chakra-petch-600-latin-ext-140bd5c4.woff2",
  "./fonts/chakra-petch-600-vietnamese-752ec6b8.woff2",
  "./fonts/chakra-petch-700-latin-3c2433eb.woff2",
  "./fonts/chakra-petch-700-latin-ext-afe317b1.woff2",
  "./fonts/chakra-petch-700-vietnamese-48dcd6d3.woff2",
  "./fonts/ft-cyr-8b46d572.woff2",
  "./fonts/ft-dev-8b7070ef.woff2",
  "./fonts/ft-grk-b3fb8703.woff2",
  "./fonts/ft-jp-40d91d43.woff2",
  "./fonts/ft-kr-30574f3d.woff2",
  "./fonts/ft-sc-0cf9049c.woff2",
  "./fonts/ft-tc-678bdb8c.woff2",
  "./fonts/ft-th-3df9f8b8.woff2",
  "./fonts/space-grotesk-400-latin-a0d054c4.woff2",
  "./fonts/space-grotesk-400-latin-ext-054c266f.woff2",
  "./fonts/space-grotesk-400-vietnamese-d699664b.woff2"
];

self.addEventListener('install', e => {
  e.waitUntil(caches.open(CACHE)
    .then(c => c.addAll(CORE))
    .then(() => self.skipWaiting()));
});

self.addEventListener('activate', e => {
  e.waitUntil(caches.keys()
    .then(ks => Promise.all(ks.filter(k => k !== CACHE).map(k => caches.delete(k))))
    .then(() => self.clients.claim()));
});

// The document is network-first: a navigation asks the network, and only a genuine
// failure falls back to the cached copy. That is the fix for the shipped-stale-HTML
// class of bug — the previous worker answered navigations from cache, so a deployed
// update could sit unseen behind a warm cache indefinitely.
// Everything else is content-hashed in its filename, so it is cache-first and immutable.
self.addEventListener('fetch', e => {
  const req = e.request;
  if (req.method !== 'GET') return;
  const url = new URL(req.url);
  if (url.origin !== location.origin) return;   // nothing off-origin should exist; do not cache it if it does

  if (req.mode === 'navigate' || url.pathname.endsWith('/') || url.pathname.endsWith('index.html')) {
    e.respondWith(
      fetch(req).then(res => {
        if (res && res.ok) caches.open(CACHE).then(c => c.put('./index.html', res.clone())).catch(()=>{});
        return res;
      }).catch(() => caches.match('./index.html').then(hit => hit || Response.error()))
    );
    return;
  }
  e.respondWith(caches.match(req, {ignoreSearch:true}).then(hit => hit || fetch(req).then(res => {
    if (res && res.ok) caches.open(CACHE).then(c => c.put(req, res.clone())).catch(()=>{});
    return res;
  })));
});
